# Generated by Django 5.0 on 2024-06-06 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_course_customuser_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='course',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='file',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.CreateModel(
            name='developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=255, null=True)),
                ('course', models.CharField(max_length=255, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('department', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
