# Generated by Django 5.0 on 2024-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_address_remove_customuser_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='status',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
